### PR TITLE
herb, eng ench, tailor ench fixes

### PR DESCRIPTION
**Pull request by gitenarra**
Added Fire Leaf and skills requirement for Herbalism, few minor updates
Fixes Tailoring enchants
Fixes Engineering enchants

### CODE REVIEW

**Comment by gitenarra** [comment]
also fix leatherworking enchants, blacksmithing enchants and tailorworking blue gear crafting (showed another item)

**Comment by gitenarra** [comment]
additional bs and leather fixes

**Comment by gitenarra** [comment]
cata's and wotlk flask and transmute fix

**Comment by snowflame0** [comment]
looks good!

**Pull request merged**
