### PR TITLE
Update data.lua

### PR DESCRIPTION
**Pull request by Adal4**
And to get a little head start...

### CODE REVIEW

**Comment by Adal4** [comment]
I'm not sure where to put the data on Hummel, though. The normal version of Shadowfang Keep no longer appears.

**Comment by scareclaw-kashtira** [comment]
I guess the heroic version of SFK?

**Comment by snowflame0** [comment]
> I guess the heroic version of SFK? data_cata.lua

Yea, we should put it in the Cata Dungeons and Raids, I'll also just put the normal versions there too, since they are technically "new" Cata dungeons

**Comment by snowflame0** [comment]
I commented out SFK from classic data for now, as having the same instance in two different modules causes issues. I will move it to the Cata file

**Pull request merged**
